configuration architecture

diff --git a/cicd/cmd/deploy b/cicd/cmd/deploy
--- a/cicd/cmd/deploy
+++ b/cicd/cmd/deploy
@@ -1,5 +1,37 @@
 #!/bin/bash
 
+######## functions ############
+RETURN = ""
+function generate-cm() {
+	RETURN="OK"
+	if [ -f ${filepath} ]; then
+		kubectl get configmap ${cm} 2> /dev/null
+		if [ $? -eq 0 ]; then
+	  		kubectl delete configmap ${cm}
+		fi
+		kubectl create configmap ${cm} --from-env-file=${filepath}
+		if [ $? -eq 1 ]; then
+	  		echo "FAIL to create configmap ${cm}"
+	  		RETURN="NK"
+		fi
+	fi
+}
+
+function generate-secret() {
+	RETURN="OK"
+	if [ -f ${filepath} ]; then
+		kubectl get secret ${secret} 2> /dev/null
+		if [ $? -eq 0 ]; then
+	  		kubectl delete secret ${secret}
+		fi
+		kubectl create secret generic ${secret} --from-env-file=${filepath}
+		if [ $? -eq 1 ]; then
+	  		echo "FAIL to create secret ${secret}"
+	  		RETURN="NK"
+		fi
+	fi
+}
+
 echo "************* DEPLOY service *****************"
 
 # get parameters
@@ -22,18 +54,33 @@ if [ $# -eq 3 ]; then
 else
 	profile=`cat ${basedir}/src/main/resources/application.yml | grep "active: " | cut -d ":" -f2 | tr -d " "`
 fi
+if [ "${profile}" -eq "" ]; then
+  echo "CAN'T Get deployment profile"
+  exit 2
+fi
 
 if [ "${context}" == "." ]; then
 	context=`kubectl config current-context`
 fi
+
+deploy_kind="Deployment"
+lists=`cat ./deploy.yaml | grep "kind: " | cut -d ":" -f2 | tr -d " "`
+for kind in ${lists}
+do
+	if [ "${kind}" == "Deployment" ] || [ "${kind}" == "StatefulSet" ]; then
+		deploy_kind=${kind}
+                break
+	fi
+done
+
 echo ""
  
 # set variables from config.properties: converted from '.' to '_'
 echo "STEP2. Set environment variables "
 
-eval $(${basedir}/cicd/setenv ${basedir}/src/main/resources/config/application-common.properties)
+eval $(${basedir}/cicd/cmd/set-env ${basedir}/cicd/config/config-common.properties)
 if [ "${profile}" != "" ]; then
-	eval $(${basedir}/cicd/setenv ${basedir}/src/main/resources/config/application-${profile}.properties)
+	eval $(${basedir}/cicd/cmd/set-env ${basedir}/cicd/config/config-${profile}.properties)
 fi
 echo ""
 
@@ -46,14 +93,14 @@ echo ""
 # check current version
 echo "STEP4. Delete application if same version exists "
 
-CURTAG=$(kubectl get deploy ${image_repository} -o yaml | grep "image: ${image_registry}/${image_project}/${image_repository}:" | cut -d ':' -f3)
+CURTAG=$(kubectl get ${deploy_kind} ${image_repository} -o yaml | grep "image: ${image_registry}/${image_project}/${image_repository}:" | cut -d ':' -f3)
 echo "FIND CURRENT VERSION: ${CURTAG}"
 
 # 동일한 서비스의 동일한 버전이 있으면 변경내용 반영위해 기존 deployment 삭제
 if [ $? -eq 0 ] && [ "${CURTAG}" == "${image_tag}" ]; then
     echo "[${image_repository}] Same version(${image_tag}) service exists!"
 
-    kubectl delete deploy --selector="app=${image_repository}"
+    kubectl delete ${deploy_kind} --selector="app=${image_repository}"
 fi
 echo ""
 
@@ -61,40 +108,30 @@ echo ""
 echo "STEP5. Create ConfigMap "
 
 cm="${image_repository}-cm-common"
-kubectl get configmap ${cm} 2> /dev/null
-if [ $? -eq 0 ]; then
-  kubectl delete configmap ${cm}
-fi
-kubectl create configmap ${cm} --from-env-file=${basedir}/src/main/resources/config/application-common.properties
-if [ $? -eq 1 ]; then
-  echo "FAIL to create configmap ${cm}!"
-  exit 2
-fi
+filepath=${basedir}/cicd/env/cm-common.env
+generate-cm
+if [ "${RESULT}" == "NK" ]; then exit 2; fi
+
 cm="${image_repository}-cm-${profile}"
-kubectl get configmap ${cm} 2> /dev/null
-if [ $? -eq 0 ]; then
-  kubectl delete configmap ${cm}
-fi
-kubectl create configmap ${cm} --from-env-file=${basedir}/src/main/resources/config/application-${profile}.properties
-if [ $? -eq 1 ]; then
-  echo "FAIL to create configmap ${cm}!"
-  exit 2
-fi
+filepath=${basedir}/cicd/env/cm-${profile}.env
+generate-cm
+if [ "${RESULT}" == "NK" ]; then exit 2; fi
+
 echo ""
 
 # secret revise
 echo "STEP6. Create Secret "
 
-secret="${image_repository}-secret"
-kubectl get secret ${secret} 2> /dev/null
-if [ $? -eq 0 ]; then
-  kubectl delete secret ${secret}
-fi
-kubectl create secret generic ${secret} --from-env-file=${basedir}/src/main/resources/config/application-secret.properties
-if [ $? -eq 1 ]; then
-  echo "FAIL to create secret ${secret}!"
-  exit 2
-fi
+secret="${image_repository}-secret-common"
+filepath=${basedir}/cicd/env/secret-common.env
+generate-secret
+if [ "${RESULT}" == "NK" ]; then exit 2; fi
+
+secret="${image_repository}-secret-${profile}"
+filepath=${basedir}/cicd/env/secret-${profile}.env
+generate-secret
+if [ "${RESULT}" == "NK" ]; then exit 2; fi
+
 echo ""
 
 # deploy.yaml을 이용하여 배포 yaml생성
@@ -115,3 +152,5 @@ if [ $? -eq 0 ]; then
 else
     echo "******** FAIL to convert deployment yaml !!! ******** "
 fi
+
+exit 0
